export const places = [
  {
    id: 'catedral',
    nombre: 'Catedral de Sevilla',
    categoria: 'monumentos',
    lat: 37.3861,
    lng: -5.9920,
    descripcion: 'Una de las catedrales góticas más grandes del mundo.',
    imagen: require('@/assets/images/catedral.jpg'),
  },
  {
    id: 'alcazar',
    nombre: 'Real Alcázar de Sevilla',
    categoria: 'monumentos',
    lat: 37.3831,
    lng: -5.9903,
    descripcion: 'Palacio real con jardines y arquitectura mudéjar.',
    imagen: require('@/assets/images/alcazar.jpg'),
  },
  {
    id: 'plaza-espana',
    nombre: 'Plaza de España',
    categoria: 'parques',
    lat: 37.3771,
    lng: -5.9869,
    descripcion: 'Plaza monumental con canales, azulejos y parques.',
    imagen: require('@/assets/images/plazaespana.jpg'),
  },
  {
    id: 'museo-bellas-artes',
    nombre: 'Museo de Bellas Artes',
    categoria: 'museos',
    lat: 37.3935,
    lng: -5.9956,
    descripcion: 'Museo con pinturas del barroco sevillano.',
    imagen: require('@/assets/images/bellasartes.jpg'),
  },
  {
    id: 'metropol-parasol',
    nombre: 'Setas de Sevilla',
    categoria: 'monumentos',
    lat: 37.3937,
    lng: -5.9916,
    descripcion: 'Estructura moderna con mirador y mercado.',
    imagen: require('@/assets/images/setas.jpg'),
  },
];
